### ISSUE TITLE
Not conform to C++14

### ISSUE THREAD

**Issue by Mappy-team-LBS** [valhalla/midgard#32]
Hello,

When compiling Midgard on g++ 4.9.2, I get the following error : 

In file included from src/midgard/pointll.cc:2:0:
./valhalla/midgard/util.h:127:67: error: converting to 'std::unordered_set<std::basic_string<char> >' from initializer list would use explicit constructor 'std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = std::basic_string<char>; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::basic_string<char> >]'
   memory_status(const std::unordered_set<std::string> interest = {});

You'll get the explanation and workaround here :
http://stackoverflow.com/questions/26947704/implicit-conversion-failure-from-initializer-list

**Comment by kevinkreiser** [comment]
thanks, having a look!

**Comment by kevinkreiser** [comment]
we probably have more of these throughout the code and will have to pick them off as we see them. thanks for pointing this out to us!
