### ISSUE TITLE
Test failure on OpenBSD

### ISSUE THREAD

**Issue by bentley** [valhalla/midgard#49]
OpenBSD 5.8 snapshot, GCC 4.9.2

    make  check-TESTS
    PASS: test/logging
    PASS: test/point2
    PASS: test/distanceapproximator
    PASS: test/aabb2
    PASS: test/obb2
    PASS: test/linesegment2
    PASS: test/vector2
    PASS: test/polyline2
    PASS: test/pointll
    PASS: test/ellipse
    PASS: test/encode
    PASS: test/tiles
    FAIL: test/util
    ============================================================================
    Testsuite summary for midgard 0.0.1
    ============================================================================
    # TOTAL: 13
    # PASS:  12
    # SKIP:  0
    # XFAIL: 0
    # FAIL:  1
    # XPASS: 0
    # ERROR: 0
    ============================================================================
    See ./test-suite.log
    Please report to https://github.com/valhalla/midgard/issues
    ============================================================================

    =====================================
       midgard 0.0.1: ./test-suite.log
    =====================================
    
    # TOTAL: 13
    # PASS:  12
    # SKIP:  0
    # XFAIL: 0
    # FAIL:  1
    # XPASS: 0
    # ERROR: 0
    
    .. contents:: :depth: 2
    
    FAIL: test/util
    ===============
    
    === Testing util ===
                   TestGetTurnDegree  [PASS]
                         TestGetTime  [PASS]
                           AppxEqual  [PASS]
                        MemoryStatus  [FAIL: Missing memory statistic for VmSize]
                           TestClamp  [PASS]
    === Failed 1 tests ===
    FAIL test/util (exit status: 1)

**Comment by kevinkreiser** [comment]
I dont have access to a bsd system. Can you please open a terminal and do `cat /proc/self/status` and paste the results here.

Thanks!

**Comment by kevinkreiser** [comment]
so yeah this little tool makes use of procfs but openbsd has disabled that.. rather than figuring out a cross platform way to do this non-critical functionality i've changed the test not to check in the case that the os doesnt have this feature

**Comment by kevinkreiser** [comment]
@bentley can you confirm that this test no longer fails on your platform?

**Comment by bentley** [comment]
Sorry for the delayed reply. Yes, all midgard tests now pass on OpenBSD.
